// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQeWiUxTfN3JYsOs1snUVcxzcgbAEWzV8',
    appId: '1:963838788300:web:b64a19232aa255e446f869',
    messagingSenderId: '963838788300',
    projectId: 'allfluttertutorial',
    authDomain: 'allfluttertutorial.firebaseapp.com',
    storageBucket: 'allfluttertutorial.appspot.com',
    measurementId: 'G-M5N506F9JS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyzhRq1Y9_sT_rqmmEqJNV2TFDttRMjTA',
    appId: '1:963838788300:android:9bfc12231b534c8746f869',
    messagingSenderId: '963838788300',
    projectId: 'allfluttertutorial',
    storageBucket: 'allfluttertutorial.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIzJs3tdXSN1p9NDgpMcR3BTX53uu7N2E',
    appId: '1:963838788300:ios:49151da12e8230ae46f869',
    messagingSenderId: '963838788300',
    projectId: 'allfluttertutorial',
    storageBucket: 'allfluttertutorial.appspot.com',
    iosBundleId: 'com.example.allFlutterTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIzJs3tdXSN1p9NDgpMcR3BTX53uu7N2E',
    appId: '1:963838788300:ios:49151da12e8230ae46f869',
    messagingSenderId: '963838788300',
    projectId: 'allfluttertutorial',
    storageBucket: 'allfluttertutorial.appspot.com',
    iosBundleId: 'com.example.allFlutterTutorial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQeWiUxTfN3JYsOs1snUVcxzcgbAEWzV8',
    appId: '1:963838788300:web:5ecb451bda9d9e8c46f869',
    messagingSenderId: '963838788300',
    projectId: 'allfluttertutorial',
    authDomain: 'allfluttertutorial.firebaseapp.com',
    storageBucket: 'allfluttertutorial.appspot.com',
    measurementId: 'G-HJS4RMZTVZ',
  );
}
